#!/usr/bin/env python
# encoding: utf-8
'''
@author: Carl
        ｛源前｝
@License: (C) Copyright 2013-2017, Node Supply Chain Manager Corporation Limited.
@Contact: 520liyuan1314@gmail.com 源前
          291437965@qq.com 
@SoftWare: PyCharm
@FileName: py04_数据类型.py
@Time: 2020/2/27 11:26
@desc:
'''

'''
三种不同类型的值的可用写法
a=10
a=100
a=-786
a=80
a=-490
a=-0x260
a=0x69

b=0.0
b=222.2
b=-21.9
b=32.3e+18
b=-90
b=-32.54e1000
b=70.2e-12

c=3.14j
c=45.j
c=9.322e-36j
c=879j
c=-6545+0j
c=3e+26j
'''

a,b=10,20
print(a==b)
c**=a